name: MetalPrints
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5589
title: The Art of Jacques Hinkle on Stainless and Acrylic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#403543'
    - '#010101'
    - '#9592b3'
    - '#ac7368'
    - '#edc9b8'
  brandStrength: 1
  lightness: 0
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
