name: MetalPrints
favicon: null
layout_spectrum: 0.7926051809918135
typography_spectrum: 0.680219201836735
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8518983747344464
  lightness: 0.26919921138323843
  saturation: 0.2312071470078081
  rhythmicContrast: 0.9776258724741638
purpose: []
